### ISSUE TITLE
新

### ISSUE THREAD

**Issue by TakahiroYamamoto** [fumimi2you/Mason#5]

**Comment by TakahiroYamamoto** [comment]
コード
let json = {
    'imagePath':__dirname + '/upload/' + req.query.filename,
    "addContourSeeds":[
      { "x":x+10, "y":y+10 },
      { "x":x+10, "y":y-10 },
      { "x":x-10, "y":y+10 },
      { "x":x-10, "y":y-10 }
    ]
  }

エラー
Traceback (most recent call last):
  File "../Python/Mason/Mason.py", line 260, in <module>
    cont_list_Array = ReFineCont(cont_array_valid, cont_array_invalid, img_seg, 4)
  File "../Python/Mason/Mason.py", line 59, in ReFineCont
    cv2.drawContours( img, cont_array_valid, -1, (255, 255, 255 ), -1 )
cv2.error: OpenCV(3.4.5) /io/opencv/modules/imgproc/src/drawing.cpp:2608: error: (-215:Assertion failed) reader.ptr != NULL in function 'cvDrawContours'

新しいapiの使い方、間違ってます？

**Comment by fumimi2you** [comment]
ん、jsonの数値のフィールドに、x+10とか設定してる？？

**Comment by TakahiroYamamoto** [comment]
一片が20の正方形にしてる感じです。

**Comment by TakahiroYamamoto** [comment]
sampleフォルダのjsonを動くものに更新してほしいっすー。

**Comment by fumimi2you** [comment]
socket通信方式に変更したpyを作っちゃいました。

そして、実行イメージの動画と、その時の通信( JSON )をSampleに突っ込んだので参照してください。

**Comment by fumimi2you** [comment]
てゆか、一回合宿やろうぜー。
